apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth
spec:
  forwardAuth:
    address: https://chimera.local/auth
    tls:
      insecureSkipVerify: true
    trustForwardHeader: true
