pomerium:
  authenticate:
    existingTLSSecret: pomerium-tls
    idp:
      provider: "github"
      clientID: d90a7611b90e3f5f82c4
      clientSecret: 0c8748bef76fdeef0af6775abf35f7cb5773d5e8
      serviceAccount: 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
    proxied: false

  proxy:
    existingTLSSecret: pomerium-tls

  databroker:
    existingTLSSecret: pomerium-tls
    storage:
      connectionString: rediss://pomerium-redis-master.pomerium.svc.cluster.local
      type: redis
      clientTLS:
        existingSecretName: pomerium-tls
        existingCASecretKey: ca.crt

  authorize:
    existingTLSSecret: pomerium-tls

  redis:
    enabled: true
    auth:
      enabled: false
    usePassword: false
    generateTLS: false
    tls:
      certificateSecret: pomerium-redis-tls

  config:
    rootDomain: chimera.local
    sharedSecret: R0+XRoGVpcoi4PfB8tMlvnrS5XUasO+D1frAEdYcYjs=
    cookieSecret: FLPCOQKigK5EQnyXlBhchl5fgzNKqi3ubtvOGt477Dg=
    generateTLS: true
    policy:
      - from: https://chimera.local
        to: http://hello-nginx
        allowed_domains:
          - gmail.com
  ingress:
    annotations:
      traefik.ingress.kubernetes.io/router.tls: "true"
    secretName: wildcard-tls
  forwardAuth:
    enabled: true
    internal: true
