apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: custom-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tarree/mip-cluster-config.git
    path: crds
    targetRevision: HEAD
  destination:
    namespace: custom-crds
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
