apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tarree/mip-cluster-config.git
    path: traefik
    targetRevision: HEAD
    helm:
      valueFiles:
        - traefik-values.yaml
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
