traefik:
  deployment:
    kind: Deployment
  service:
    enabled: true
    type: LoadBalancer
  ingressRoute:
    dashboard:
      enabled: true
  ports:
    traefik:
      expose: true
  providers:
    kubernetesCRD:
      allowCrossNamespace: true
