traefik:
  deployment:
    kind: Deployment
  service:
    enabled: true
    type: LoadBalancer
  ingressRoute:
    dashboard:
      enabled: true
  ports:
    traefik:
      expose: true
  providers:
    kubernetesCRD:
      allowCrossNamespace: true
  logs:
    # Traefik logs concern everything that happens to Traefik itself (startup, configuration, events, shutdown, and so on).
    general:
      # By default, the logs use a text format (common), but you can
      # also ask for the json format in the format option
      # format: json
      # By default, the level is set to ERROR. Alternative logging levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
      level: DEBUG
    access:
      # To enable access logs
      enabled: true
