apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-local
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  storage: "lvm"
  volgroup: "chimera-lvmvg"
volumeBindingMode: WaitForFirstConsumer
provisioner: local.csi.openebs.io
